## From https://www.r-bloggers.com/deploying-an-r-shiny-app-with-docker/
## and https://www.bjoern-hartmann.de/post/learn-how-to-dockerize-a-shinyapp-in-7-steps/
##

#------------------------------------------------------------
# Start from lastest base+data image
#------------------------------------------------------------

FROM bigomics/omicsplayground:build

#------------------------------------------------------------
# Install extra packages required since base
#------------------------------------------------------------

# RUN apt install -y xvfb
# RUN R -e "BiocManager::install(c('randomForest'))"
# RUN pip install umap-learn

#------------------------------------------------------------
# Pull latest from GitHub
#------------------------------------------------------------
WORKDIR /omicsplayground
RUN git pull

#------------------------------------------------------------
# Copy further configuration files into the Docker image
#------------------------------------------------------------
COPY docker/shiny-server.conf /etc/shiny-server/shiny-server.conf
COPY docker/shiny-server.sh /usr/bin/shiny-server.sh
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

EXPOSE 3838

CMD ["/usr/bin/shiny-server.sh"]
