## From https://www.r-bloggers.com/deploying-an-r-shiny-app-with-docker/
## and https://www.bjoern-hartmann.de/post/learn-how-to-dockerize-a-shinyapp-in-7-steps/
##

#------------------------------------------------------------
# Start from lastest base+data image
#------------------------------------------------------------

FROM bigomics/omicsplayground:base
##FROM bigomics/omicsplayground:v2.3.0

#------------------------------------------------------------
# Arghh... we forgot shiny-server...
#------------------------------------------------------------

RUN wget -nv https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.14.948-amd64.deb \
    && sudo gdebi shiny-server-1.5.14.948-amd64.deb

#------------------------------------------------------------
# Install any extra packages required since base
#------------------------------------------------------------

# RUN apt install -y xvfb
# RUN R -e "devtools::install_version('mnormt', version='1.5-7')" \
#    && R -e "install.packages(c())"
RUN R -e "BiocManager::install(c('rhdf5','mygene','qgraph', \
    'psych','metap','brew','Seurat'))"
# RUN R -e "install.packages(c('rhdf5'))"
# RUN pip3 install umap-learn

#------------------------------------------------------------
# Clone fresh code from GitHub
#------------------------------------------------------------
WORKDIR /
RUN rm -fr /omicsplayground \
    && git clone https://github.com/bigomics/omicsplayground.git \
#   && rm -fr /omicsplayground/.git \
    && chmod -R ugo+rwX /omicsplayground 

WORKDIR /omicsplayground
RUN git pull

#------------------------------------------------------------
# Copy any extra data sets into Docker image
#------------------------------------------------------------
WORKDIR /omicsplayground
## RUN R -e "setwd('scripts');source('build-datasets.R')"
COPY data/geiger2016-arginine.pgx data/GSE72056-scmelanoma.pgx \
   data/GSE22886-immune.pgx data/tcga-brca_pub.pgx data/
RUN R -e "setwd('data');source('init.R')"

#------------------------------------------------------------
# Update configuration files into the Docker image
#------------------------------------------------------------
WORKDIR /omicsplayground
COPY docker/shiny-server.conf /etc/shiny-server/shiny-server.conf
COPY docker/shiny-server.sh /usr/bin/shiny-server.sh
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

EXPOSE 3838
CMD ["/usr/bin/shiny-server.sh"]
