##
## This file is part of the Omics Playground project.
## Copyright (c) 2018-2020 BigOmics Analytics Sagl. All rights reserved.
##

## Start from base image, update git code and add data
## folder. Create docker ready to be deployed.

#------------------------------------------------------------
# Start from lastest base image
#------------------------------------------------------------

FROM bigomics/omicsplayground-base:ub2204_v3

ARG BRANCH=master
RUN echo "Updating omicsplayground-base:ub2204_v3 image..."

#------------------------------------------------------------
# Install any extra (forgotten...) Ubuntu libs
#------------------------------------------------------------
ENV DEBIAN_FRONTEND noninteractive

#------------------------------------------------------------
# Install updated libraries
#------------------------------------------------------------

RUN echo "Step 1: Install updated libraries"

# This can be removed once new base is built
RUN R -e "remotes::install_version('Matrix', version = '1.6.3')"
RUN R -e "install.packages('plsRcox', dependencies = FALSE)"

# NEW INSTALLS THAT ARE BOTH IN OPG-BASE (can be removed when base v4 is built)
RUN echo "Step 2: Install updated libraries"

# sf also added in requirements (check before removing!)
RUN R -e "install.packages('shinybrowser')"
RUN R -e "install.packages('sf')"

RUN echo "Step 3: Install supporting bigomics  (as R packages)"
# This can be removed once new base is built 
RUN R -e "remotes::install_version('matrixStats',version='1.1.0',force=TRUE)"

RUN echo "Step 4: Install updated libraries"
RUN R -e "install.packages(c('spatstat.utils', 'spatstat.data', 'spatstat.core'), repos = 'https://spatstat.r-universe.dev', dependencies=FALSE)"
RUN R -e "remotes::install_version('rgeos', version = '0.6-4')"
RUN R -e "remotes::install_github('cran/Matrix', ref = '23d9d53')"
RUN R -e "remotes::install_version('SeuratObject', '4.1.4', repos = c('https://satijalab.r-universe.dev', getOption('repos')), dependencies=FALSE)"
RUN R -e "remotes::install_version('Seurat', '4.1.0', repos = c('https://satijalab.r-universe.dev', getOption('repos')), dependencies=FALSE)"

RUN echo "Step 4.5: Install updated libraries"
RUN R -e "BiocManager::install('org.Rn.eg.db', dependencies = NA, force = FALSE, ask = FALSE, update = FALSE)"
RUN R -e "BiocManager::install('AnnotationHub',dependencies = NA, force = FALSE, ask = FALSE, update = FALSE)"
RUN R -e "devtools::install_version('dbplyr', version = '2.3.4', dependencies=FALSE)"

RUN echo "Step 5: Finished Install updated libraries"
RUN R -e "install.packages('grr', dependencies=FALSE)" 
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.8.tar.gz', type = 'source', repos = NULL)"
RUN R -e "BiocManager::install('orthogene', dependencies = NA, force = FALSE, ask = FALSE, update = FALSE)"

RUN echo "Step 6: Finished Install updated libraries"

#------------------------------------------------------------
# Pre-run AnnotationHub
#------------------------------------------------------------

## initialize AnnotationHub
COPY dev/init_annothub.R dev/init_annothub.R
RUN Rscript dev/init_annothub.R
