FROM ubuntu:20.04

MAINTAINER Ivo Kwee "kwee@bigomics.ch"

# =====================================================================
# Create docker image for Omics Playground 
# =====================================================================

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y \
    apt-utils software-properties-common \
    libcurl4-gnutls-dev libnode-dev \
    libssl-dev libxml2-dev libjpeg-dev \
    libgl-dev libglu-dev tk-dev libhdf5-dev \
    libgit2-dev libssh2-1-dev libnetcdf-dev \
    libudunits2-dev libgdal-dev libbz2-dev \
    jags emacs git procps htop \
    python3 python3-pip python-is-python3 \
    pdftk vim-tiny less wget gdebi-core \
    pandoc pandoc-citeproc phantomjs \ 
    libcairo2-dev libxt-dev xvfb 
    
# Install basic stuff and R
RUN apt install -y r-base r-base-dev r-recommended

# Install shiny-server
RUN wget -nv https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.14.948-amd64.deb \
    && sudo gdebi shiny-server-1.5.14.948-amd64.deb

# Install Plotly/Orca server
RUN wget -nv https://github.com/plotly/orca/releases/download/v1.3.1/orca-1.3.1.AppImage \
    && mv orca-1.3.1.AppImage /usr/local/bin/ 
COPY ext/bin/orca /usr/local/bin/ 
RUN chmod ugo+x /usr/local/bin/orca-1.3.1.AppImage \
    && chmod ugo+x /usr/local/bin/orca   

#------------------------------------------------------------
# Install R packages that are required
#------------------------------------------------------------

RUN rm -fr /omicsplayground
WORKDIR /omicsplayground
COPY R /omicsplayground/R
COPY shiny /omicsplayground/shiny

## auto detected packages
RUN R -e "setwd('R');source('requirements.R')"

## any missing packages
RUN R -e "install.packages(c('umap','corrplot','wordcloud', \
    'metap','brew','Seurat','R.utils','rhdf5', 'mygene', \
    'qgraph','psych'))"
RUN R -e "BiocManager::install(c('rhdf5'))"
RUN rm -fr /omicsplayground/R /omicsplayground/shiny

#------------------------------------------------------------
# Add shiny user to group shiny
#------------------------------------------------------------
RUN groupadd  shiny \
    && useradd --gid shiny --shell /bin/bash --create-home shiny

#------------------------------------------------------------
# Clean up when done.
#------------------------------------------------------------
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#------------------------------------------------------------
# Copy further configuration files into the Docker image
#------------------------------------------------------------
RUN mkdir -p /var/lib/shiny-server/bookmarks/shiny
COPY docker/shiny-server.conf /etc/shiny-server/shiny-server.conf
COPY docker/shiny-server.sh /usr/bin/shiny-server.sh
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

## EXPOSE 3838
## CMD ["/usr/bin/shiny-server.sh"]
