FROM ubuntu:20.04

MAINTAINER Ivo Kwee "kwee@bigomics.ch"

# =====================================================================
# R
# =====================================================================

# Need this to add R repo
RUN apt update && apt install -y \
    apt-utils software-properties-common

# Add R apt repository
#RUN add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/"
#RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

RUN DEBIAN_FRONTEND=noninteractive apt install -y \
    libcurl4-gnutls-dev libnode-dev \
    libssl-dev libxml2-dev libjpeg-dev \
    libgl-dev libglu-dev tk-dev libhdf5-dev \
    libgit2-dev libssh2-1-dev libnetcdf-dev \
    libudunits2-dev libgdal-dev libbz2-dev \
    jags emacs git procps htop \
    python3 python3-pip python-is-python3 \
    pdftk vim-tiny less wget gdebi-core \
    pandoc pandoc-citeproc phantomjs \ 
    libcairo2-dev libxt-dev xvfb 
    
# Install basic stuff and R
RUN apt install -y r-base r-base-dev r-recommended

# Install Plotly/Orca server
COPY ext/bin/orca /usr/local/bin/orca 
RUN wget https://github.com/plotly/orca/releases/download/v1.3.1/orca-1.3.1.AppImage \
    && mv orca-1.3.1.AppImage /usr/local/bin \
    && chmod ugo+x /usr/local/bin/orca-1.3.1.AppImage /usr/local/bin/orca   

#------------------------------------------------------------
# Install R packages that are required
#------------------------------------------------------------
## Remove old folder
RUN rm -fr /omicsplayground /var/lib/shiny-server/bookmarks/shiny \
    && mkdir -p /var/lib/shiny-server/bookmarks/shiny \
    && mkdir -p /omicsplayground

## Clone clean install from GitHub and remove .git folder
WORKDIR /
RUN rm -fr /omicsplayground \
    && git clone https://github.com/bigomics/omicsplayground.git \
    && chmod -R ugo+rwX /omicsplayground \
    && rm -fr /omicsplayground/.git

## install R packages
WORKDIR /omicsplayground
RUN R -e "setwd('R');source('requirements.R')"
RUN R -e "install.packages(c('umap','corrplot','wordcloud', \
    'metap','brew','Seurat','R.utils'))"

#------------------------------------------------------------
# Build default data sets 
#------------------------------------------------------------
WORKDIR /omicsplayground
RUN R -e "setwd('scripts');source('build-datasets.R')" \
    && R -e "setwd('data');source('init.R')"

#------------------------------------------------------------
# Add shiny user to group shiny
#------------------------------------------------------------
RUN groupadd  shiny \
    && useradd --gid shiny --shell /bin/bash --create-home shiny

#------------------------------------------------------------
# Copy further configuration files into the Docker image
#------------------------------------------------------------
WORKDIR /omicsplayground
COPY docker/shiny-server.conf /etc/shiny-server/shiny-server.conf
COPY docker/shiny-server.sh /usr/bin/shiny-server.sh
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

EXPOSE 3838
CMD ["/usr/bin/shiny-server.sh"]
