##
## This file is part of the Omics Playground project.
## Copyright (c) 2018-2020 BigOmics Analytics Sagl. All rights reserved.
##

FROM ubuntu:21.04
##FROM ubuntu:20.10

MAINTAINER Ivo Kwee "kwee@bigomics.ch"

# =====================================================================
# Creates base docker image for Omics Playground. Generally not for
# direct deployment but as base image for further build. Install
# necessary Debian packages and R packages 
# =====================================================================

ENV DEBIAN_FRONTEND noninteractive

# Hirsute (21.04) has been moved..
RUN sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

RUN apt update && apt install -y \
    locales apt-utils software-properties-common \
    libcurl4-gnutls-dev libnode-dev libv8-dev \
    libssl-dev libxml2-dev libjpeg-dev \
    libgl-dev libglu-dev tk-dev libhdf5-dev \
    libgit2-dev libssh2-1-dev libnetcdf-dev \
    libudunits2-dev libgdal-dev libbz2-dev \
    jags emacs git procps htop \
    python3 python3-pip python-is-python3 \
    pdftk vim-tiny less wget gdebi-core \
    pandoc pandoc-citeproc imagemagick \ 
    libcairo2-dev libxt-dev xvfb \
    libfftw3-dev 

# Set the locale to UTF8
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 

# set bash (not dash) as default shell
RUN ln -fs /bin/bash /bin/sh 

# Install basic stuff and R
RUN apt install -y r-base r-base-dev r-recommended
RUN apt install -y libharfbuzz-dev libfribidi-dev

#------------------------------------------------------------
# Install R packages that are required
#------------------------------------------------------------

RUN rm -fr /omicsplayground
WORKDIR /omicsplayground
COPY R /omicsplayground/R
COPY shiny /omicsplayground/shiny

## base packages
RUN R -e "install.packages(c('devtools','remotes','reticulate'))"
RUN R -e "remotes::install_github('JohnCoene/firebase@omics')" 

## any required/manual packages
RUN R -e "install.packages(c('umap','corrplot','wordcloud', \
    'metap','brew','Seurat','R.utils', 'qgraph','psych', \
    'pryr','shinycssloaders','rpart.plot'))"

## auto detected packages
RUN R -e "setwd('R');source('requirements.R')"
RUN R -e "install.packages(c('BiocManager'))"
RUN R -e "BiocManager::install(c('rhdf5','monocle','mygene','edgeR','DESeq2'))"


#------------------------------------------------------------
# Add shiny user to group shiny
#------------------------------------------------------------
RUN groupadd  shiny \
    && useradd --gid shiny --shell /bin/bash --create-home shiny

#------------------------------------------------------------
# Clean up when done.
#------------------------------------------------------------
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

#------------------------------------------------------------
#----------------------- END --------------------------------
#------------------------------------------------------------

## NOTHING