## From https://www.r-bloggers.com/deploying-an-r-shiny-app-with-docker/
## and https://www.bjoern-hartmann.de/post/learn-how-to-dockerize-a-shinyapp-in-7-steps/
##

#------------------------------------------------------------
# Start from lastest base image
#------------------------------------------------------------

FROM bigomics/omicsplayground:base

#------------------------------------------------------------
## Install needed R packages that are required
#------------------------------------------------------------
## RUN R -e "install.packages(c('umap','corrplot','wordcloud'))"
## RUN pip install umap-learn

#------------------------------------------------------------
## Pull from GitHub
#------------------------------------------------------------
RUN git clone https://github.com/bigomics/omicsplayground.git && chmod -R ugo+rwX /omicsplayground

#------------------------------------------------------------
# Copy local data into Docker image
#------------------------------------------------------------
COPY data/* /omicsplayground/data/
RUN R -e "setwd('data');source('init.R')"

#------------------------------------------------------------
# Copy further configuration files into the Docker image
#------------------------------------------------------------
COPY docker/shiny-server.conf  /etc/shiny-server/shiny-server.conf
COPY docker/shiny-server.sh /usr/bin/shiny-server.sh

EXPOSE 3838

CMD ["/usr/bin/shiny-server.sh"]
