##
## This file is part of the Omics Playground project.
## Copyright (c) 2018-2020 BigOmics Analytics Sagl. All rights reserved.
##

FROM ubuntu:22.04
##FROM ubuntu:20.10
##FROM ubuntu:20.04

MAINTAINER Ivo Kwee "kwee@bigomics.ch"

# =====================================================================
# Creates base docker image for Omics Playground. Generally not for
# direct deployment but as base image for further build. Install
# necessary Debian packages and R packages 
# =====================================================================

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y \
    locales apt-utils software-properties-common \
    libcurl4-gnutls-dev libnode-dev libv8-dev \
    libssl-dev libxml2-dev libjpeg-dev \
    libgl-dev libglu-dev tk-dev libhdf5-dev \
    libgit2-dev libssh2-1-dev libnetcdf-dev \
    libudunits2-dev libgdal-dev libbz2-dev \
    jags emacs git procps htop \
    python3 python3-pip python-is-python3 \
    pdftk vim-tiny less wget gdebi-core \
    pandoc pandoc-citeproc imagemagick \ 
    libcairo2-dev libxt-dev xvfb \
    libfftw3-dev 

# Set the locale to UTF8
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 

# Install basic stuff and R
RUN apt install -y r-base r-base-dev r-recommended

#------------------------------------------------------------
# Clone fresh code from GitHub
#------------------------------------------------------------
#WORKDIR /
#RUN wget https://github.com/bigomics/omicsplayground/archive/develop.zip \
#    && unzip develop.zip && mv omicsplayground-develop omicsplayground \
#    && chmod -R ugo+rwX /omicsplayground 

#------------------------------------------------------------
# Install R packages that are required
#------------------------------------------------------------
WORKDIR /omicsplayground

## restore using renv
COPY renv.lock renv.locak
RUN R -e "install.packages(renv);renv::restore()"

## any missing packages
#RUN R -e "install.packages(c('umap','corrplot','wordcloud', \
#    'metap','brew','Seurat','R.utils', 'qgraph','psych'))"
#RUN R -e "BiocManager::install(c('rhdf5', 'monocle', 'mygene'))"

#------------------------------------------------------------
# Clean up when done.
#------------------------------------------------------------
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

#------------------------------------------------------------
# Copy further configuration files into the Docker image
#------------------------------------------------------------
#RUN mkdir -p /var/lib/shiny-server/bookmarks/shiny
#COPY docker/shiny-server.conf /etc/shiny-server/shiny-server.conf
#COPY docker/shiny-server.sh /usr/bin/shiny-server.sh

## EXPOSE 3838
## CMD ["/usr/bin/shiny-server.sh"]
