##
## This file is part of the Omics Playground project.
## Copyright (c) 2018-2020 BigOmics Analytics Sagl. All rights reserved.
##

## Start from base image, update git code and add data
## folder. Create docker ready to be deployed.

#------------------------------------------------------------
# Start from lastest base image
#------------------------------------------------------------

FROM bigomics/omicsplayground:base
##FROM bigomics/omicsplayground:v2.3.0

#------------------------------------------------------------
# Install any extra (forgotten...) packages since base
#------------------------------------------------------------

# RUN apt install -y xvfb
# RUN R -e "devtools::install_version('mnormt', version='1.5-7')" \
#    && R -e "install.packages(c())"
RUN R -e "install.packages(c('shinythemes'))"
RUN R -e "BiocManager::install(c('TxDb.Hsapiens.UCSC.hg19.knownGene','TxDb.Mmusculus.UCSC.mm10.knownGene'))"
# RUN pip3 install umap-learn

#------------------------------------------------------------
# Clone fresh code from GitHub
#------------------------------------------------------------
# WORKDIR /
# RUN rm -fr /omicsplayground \
#     && git clone https://github.com/bigomics/omicsplayground.git \
# #   && rm -fr /omicsplayground/.git \
#     && chmod -R ugo+rwX /omicsplayground 

#------------------------------------------------------------
# Update code from GitHub
#------------------------------------------------------------
WORKDIR /omicsplayground
RUN git pull

#------------------------------------------------------------
# Copy any extra data sets into Docker image
#------------------------------------------------------------
WORKDIR /omicsplayground
## RUN R -e "setwd('scripts');source('build-datasets.R')"
COPY data/geiger2016-arginine.pgx data/GSE72056-scmelanoma.pgx \
   data/GSE22886-immune.pgx data/tcga-brca_pub.pgx data/
RUN R -e "setwd('data');source('init.R')"

#------------------------------------------------------------
# Update configuration files into the Docker image
#------------------------------------------------------------
WORKDIR /omicsplayground
COPY docker/shiny-server.conf /etc/shiny-server/shiny-server.conf
COPY docker/shiny-server.sh /usr/bin/shiny-server.sh
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

EXPOSE 3838
CMD ["/usr/bin/shiny-server.sh"]
