# Base image https://hub.docker.com/u/rocker/
FROM rocker/shiny:4.1.3

# system libraries of general use
## install debian packages
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
    libxml2-dev \
    libcairo2-dev \
    libsqlite3-dev \
    libmariadbd-dev \
    libpq-dev \
    libssh2-1-dev \
    unixodbc-dev \
    libcurl4-openssl-dev \
    libsodium-dev \
    libssl-dev \
    pandoc pandoc-citeproc imagemagick \
    libbz2-dev liblzma-dev \
    libgl-dev libglu-dev tk-dev libhdf5-dev libglpk-dev 

## update system libraries
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean

# Set the locale to UTF8
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 

#------------------------------------------------------------
# Clone fresh code from GitHub
#------------------------------------------------------------
#WORKDIR /
#RUN wget https://github.com/bigomics/omicsplayground/archive/develop.zip \
#    && unzip develop.zip && mv omicsplayground-develop omicsplayground \
#    && chmod -R ugo+rwX /omicsplayground 

#------------------------------------------------------------
# Install R packages that are required
#------------------------------------------------------------
WORKDIR /omicsplayground

# restore using renv
## Pin renv version
ENV RENV_VERSION 0.15.4
RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv@${RENV_VERSION}')"

# manual fixing because of gigantic package messup
RUN R -e "remotes::install_github('JohnCoene/firebase@omics')"
RUN R -e "remotes::install_github('bigomics/bigdash')" 
RUN R -e "install.packages(c('shinylogs','shinycssloaders','concaveman','ggtext','sass', 'reticulate'))"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/locfit/locfit_1.5-9.4.tar.gz')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/randomForest/randomForest_4.6-14.tar.gz')"
# RUN R -e "BiocManager::install(c('edgeR','DESeq2'))"
# RUN pip3 install umap-learn
RUN R -e "reticulate::install_miniconda()"

# copy necessary files
## renv lockfile
COPY renv.lock /renv.lock

# install renv & restore packages
RUN Rscript -e 'renv::consent(provided = TRUE)'
RUN Rscript -e 'renv::restore()'
