## From https://www.r-bloggers.com/deploying-an-r-shiny-app-with-docker/
## and https://www.bjoern-hartmann.de/post/learn-how-to-dockerize-a-shinyapp-in-7-steps/
##

#------------------------------------------------------------
# Start from lastest base+data image
#------------------------------------------------------------

FROM bigomics/omicsplayground:testing

#------------------------------------------------------------
# Install extra packages required since base (later move to requirements.R!)
#------------------------------------------------------------

RUN apt-get install -y pdftk libbz2-dev
RUN R -e "install.packages(c('shinydashboardPlus','optparse','docopt','randomForest'))"
RUN R -e "BiocManager::install(c('rgeolocate','rworldmap','randomForest'))"
RUN R -e "BiocManager::install(c('org.Mm.eg.db','EnsDb.Hsapiens.v86','EnsDb.Mmusculus.v79'))"

#------------------------------------------------------------x
## Pull from GitHub
#------------------------------------------------------------
WORKDIR /omicsplayground
RUN rm data/geiger2016-arginine.pgx
RUN git pull

#------------------------------------------------------------
# Copy local data into Docker image
#------------------------------------------------------------
WORKDIR /omicsplayground
## COPY data-examples/* data/
COPY data-examples/geiger2016-arginine.pgx data/
## RUN R -e "setwd('data');source('init.R')"

#------------------------------------------------------------
# Copy further configuration files into the Docker image
#------------------------------------------------------------
COPY docker/shiny-server.conf  /etc/shiny-server/shiny-server.conf
COPY docker/shiny-server.sh /usr/bin/shiny-server.sh
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

EXPOSE 3838

CMD ["/usr/bin/shiny-server.sh"]
