##
## This file is part of the Omics Playground project.
## Copyright (c) 2018-2020 BigOmics Analytics Sagl. All rights reserved.
##

FROM ubuntu:22.04 AS os-base
##FROM ubuntu:20.10
##FROM ubuntu:20.04

MAINTAINER Ivo Kwee "kwee@bigomics.ch"

# =====================================================================
# Creates base docker image for Omics Playground. Generally not for
# direct deployment but as base image for further build. Install
# necessary Debian packages and R packages 
# =====================================================================

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y \
    locales apt-utils software-properties-common \
    libcurl4-gnutls-dev libnode-dev libv8-dev \
    libssl-dev libxml2-dev libjpeg-dev \
    libgl-dev libglu-dev tk-dev libhdf5-dev \
    libgit2-dev libssh2-1-dev libnetcdf-dev \
    libudunits2-dev libgdal-dev libbz2-dev \
    jags emacs git procps htop \
    python3 python3-pip python-is-python3 \
    pdftk vim-tiny less wget gdebi-core \
    pandoc pandoc-citeproc imagemagick \ 
    libcairo2-dev libxt-dev xvfb \
    libfftw3-dev libglpk-dev librsvg2-dev \
    libgsl-dev librsvg2-dev libgsl-dev curl \
    libsodium-dev

# Install Chrome
RUN apt-get update && apt-get install -y wget gnupg2
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update && apt-get install -y google-chrome-stable

# Set the locale to UTF8
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 

# Install basic stuff and R
RUN apt install -y r-base r-base-dev r-recommended

#------------------------------------------------------------
# Install R packages that are required
#------------------------------------------------------------
FROM os-base AS r-base1
WORKDIR /

## playbase -------------------------------
RUN echo Downloading Playbase
RUN R -e "install.packages('remotes')"
RUN R -e "remotes::install_github('bigomics/playbase',dependencies=TRUE)"

## playdata: perhaps not needed because playbase already states
## playdata as dependency in DESCRIPTION file.
RUN git clone -b main --single-branch --depth 1 \
    https://github.com/bigomics/playdata.git \
    && R CMD INSTALL playdata \
    && rm -fr playdata

## Omicsplayground (partial install): this installs only the needed
## packages. The complete installation of OPG is done in the final
## Dockerfile.
RUN rm -fr /omicsplayground && mkdir -p /omicsplayground
WORKDIR /omicsplayground
COPY components /omicsplayground/components
COPY dev /omicsplayground/dev
RUN Rscript dev/requirements.R

## add any missing packages manually------------------------
FROM r-base1 AS r-base2
#RUN R -e "BiocManager::install(c('rhdf5', 'monocle', 'mygene'))"
#RUN R -e "install.packages(c('RSpectra'))"

#------------------------------------------------------------
# Clean up when done.
#------------------------------------------------------------
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

