##
## This file is part of the Omics Playground project.
## Copyright (c) 2018-2020 BigOmics Analytics Sagl. All rights reserved.
##

## Start from base image, update git code and add data
## folder. Create docker ready to be deployed.

#------------------------------------------------------------
# Start from lastest image
#------------------------------------------------------------

FROM bigomics/omicsplayground:latest-v2

#------------------------------------------------------------
# Update from local code
#------------------------------------------------------------
WORKDIR /omicsplayground
RUN rm -rf shiny/* R/*
COPY shiny/ shiny/
COPY R/ R/
COPY bin/ bin/

WORKDIR /omicsplayground
EXPOSE 3838
#CMD ["R", "-e", "shiny::runApp('shiny', port=3838, host='0.0.0.0', launch.browser=0)"]
CMD exec R -e "shiny::runApp('shiny', port=3838, host='0.0.0.0', launch.browser=0)" 2>&1 | tee -a run.log


