name: Shinytest boards
on: 
  push:
env:
  DOCKER_TAG: masierom/omicsplayground:latest
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Print ls recursive
        run: ls -R
      -
        name: Checkout
        uses: actions/checkout@v3
      
      - 
        name: Print ls recursive after checkout
        run: ls -R
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN  }}
      
      - 
        name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: mauromiguelm
          wait-timeout-minutes: 60
      -
        name: Shinytest docker
        id: test
        run: |
          docker build -t ${{ env.DOCKER_TAG }} -f ./.github/workflows/build-test-push/Dockerfile .
          docker run --rm ${{ env.DOCKER_TAG }}
      
      - name: Upload snapshots as artifact
        uses: actions/upload-artifact@v3
        with:
          name: testthat-snapshots
          path: /omicsplayground/tests/testthat/_snaps/linux-4.1/board-values/*
          if-no-files-found: ignore
      
      - name: Configure Git
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Commit and push snapshots
        run: |
          cd ${{ github.workspace }}
          git add ./omicsplayground/tests/testthat/_snaps/linux-4.1/board-values/*
          git commit -m "Add new snapshots from testing"
          git push origin
     
      -
        name: Print git diff
        run: echo "git diff = ${{ steps.test.outputs.git_diff }}"
        
      -
        name: Print test result
        run: echo "Test result = ${{ steps.test.outputs.test_result }}"
      -
        name: Push
        if: steps.test.outputs.test_result == 'TRUE'
        run: |
          docker push ${{ env.DOCKER_TAG }}
