## https://docs.docker.com/ci-cd/github-actions

name: build-test-push
on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:

  buid-test-push:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: master
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/build-test-push/Dockerfile
          push: false
          no-cache: true
          build-args: |
            BRANCH=master
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omicsplayground:test
      -
        name: Push
        if: steps.test.outputs.test_result == 'FALSE'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/build-test-push/Dockerfile
          push: true
          no-cache: true
          build-args: |
            BRANCH=master
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omicsplayground:test
        
          
