name: Shinytest boards
on:
  schedule:
    - cron:  '0 4 * * *'
  pull_request:
  workflow_dispatch:

env:
  TEST_TAG: masierom/omicsplayground:test
  LATEST_TAG: masierom/omicsplayground:latest

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN  }}
      -
        name: Shinytest docker
        id: test
        run: |
          docker build -t ${{ env.LATEST_TAG }} -f ./.github/workflows/build-test-push/Dockerfile .
          docker run --rm -d ${{ env.LATEST_TAG }}
      
      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        with:
          name: testthat-snapshots
          path: ./omicsplayground/tests/testthat/_snaps/
          if-no-files-found: ignore
        
      -
        name: Print test result
        run: echo "Test result = ${{ steps.test.outputs.test_result }}"
      -
        name: Push
        if: steps.test.outputs.test_result == 'TRUE'
        run: |
          docker push ${{ env.TEST_TAG }}
