## https://docs.docker.com/ci-cd/github-actions

name: Shinytest boards
on:
  schedule:
    - cron:  '0 4 * * *'
  pull_request:
  workflow_dispatch:

env:
  TEST_TAG: bigomics/omicsplayground:test
  LATEST_TAG: bigomics/omicsplayground:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Shinytest docker
        run: |
          docker build -t ${{ env.TEST_TAG }} -f ./.github/workflows/build-test-push/Dockerfile .
          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Print test result
        run: echo "Test result = ${{ steps.test.outputs.test_result }}"
      -
        name: Push
        if: steps.test.outputs.test_result == 'FALSE'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/build-test-push/Dockerfile
          push: true
          no-cache: true
          build-args: |
            BRANCH=master
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omicsplayground:test