## https://docs.docker.com/ci-cd/github-actions

name: Shinytest boards
on:
  schedule:
    - cron:  '0 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:

  build-test-push:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: gha_shinytest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/build-test-push/Dockerfile
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omicsplayground:test
      - name: List images, print and run container
        id: test
        run: |
          docker images | tee images.txt
          cat images.txt
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/omicsplayground:test
      -
        name: Print test result
        run: echo "Test result = ${{ steps.test.outputs.test_result }}"
      -
        name: Push
        if: steps.test.outputs.test_result == 'FALSE'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/build-test-push/Dockerfile
          push: true
          no-cache: true
          build-args: |
            BRANCH=master
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omicsplayground:test