on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build testing
        run: |
          docker build -f docker/Dockerfile.testing -t bigomics/omicsplayground:testing .
