## https://docs.docker.com/ci-cd/github-actions

name: build Docker (testing)

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: master
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          no-cache: true
          build-args: |
            BRANCH=master
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omicsplayground:testing
  
