## https://docs.docker.com/ci-cd/github-actions

name: build Docker (dev-multi-species)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'dev-multi-species'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile_multi_species
          push: true          
          no-cache: true
          build-args: |
            BRANCH=${{ github.event.inputs.branch }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omicsplayground:${{ github.event.inputs.branch }} 
