name: update OPG version (devel)

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [devel]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update version from master
        run: |
            # Fetch master branch to get the latest VERSION
            git fetch origin master

            # Get the version number from master branch
            master_version=$(git show origin/master:VERSION)
            number_version=$(echo "$master_version" | grep -oP '\d+\.\d+\.\d+')

            # Build version string with current branch and date
            DATE=`date +%y%m%d|sed 's/\ //g'`
            BRANCH=`git rev-parse --abbrev-ref HEAD`  ## get active GIT branch
            BUILD="v"$number_version"+"$BRANCH""$DATE

            # Write the VERSION file
            echo $BUILD > VERSION

            # Set as environment variable for next steps
            echo "NEW_VERSION=$BUILD" >> $GITHUB_ENV

      - name: Commit and push version changes
        run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add VERSION
            git commit -m "Update version to $NEW_VERSION"
            git pull --ff-only
            git push origin

