##
## This file is part of the Omics Playground project.
## Copyright (c) 2018-2020 BigOmics Analytics Sagl. All rights reserved.
##

FROM ubuntu:21.04
##FROM ubuntu:20.10
##FROM ubuntu:20.04

MAINTAINER Ivo Kwee "kwee@bigomics.ch"

# =====================================================================
# Creates base docker image for Omics Playground. Generally not for
# direct deployment but as base image for further build. Install
# necessary Debian packages and R packages 
# =====================================================================

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y \
    locales apt-utils software-properties-common \
    libcurl4-gnutls-dev libnode-dev libv8-dev \
    libssl-dev libxml2-dev libjpeg-dev \
    libgl-dev libglu-dev tk-dev libhdf5-dev \
    libgit2-dev libssh2-1-dev libnetcdf-dev \
    libudunits2-dev libgdal-dev libbz2-dev \
    jags emacs git procps htop \
    python3 python3-pip python-is-python3 \
    pdftk vim-tiny less wget gdebi-core \
    pandoc pandoc-citeproc imagemagick \ 
    libcairo2-dev libxt-dev xvfb \
    libfftw3-dev 

# Set the locale to UTF8
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 

# Install basic stuff and R
RUN apt install -y r-base r-base-dev r-recommended

# Install shiny-server
#RUN wget -nv https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.14.948-amd64.deb \
#    && gdebi shiny-server-1.5.14.948-amd64.deb

#------------------------------------------------------------
# Install R packages that are required
#------------------------------------------------------------

RUN rm -fr /omicsplayground
WORKDIR /omicsplayground
COPY R /omicsplayground/R
COPY shiny /omicsplayground/shiny

## auto detected packages
RUN R -e "setwd('R');source('requirements.R')"

## any missing packages
RUN R -e "install.packages(c('umap','corrplot','wordcloud', \
    'metap','brew','Seurat','R.utils', 'qgraph','psych'))"
RUN R -e "BiocManager::install(c('rhdf5', 'monocle', 'mygene'))"

#------------------------------------------------------------
# Clone fresh code from GitHub
#------------------------------------------------------------
WORKDIR /
#RUN rm -fr /omicsplayground/R /omicsplayground/shiny
#RUN rm -fr /omicsplayground \
#    && git clone https://github.com/bigomics/omicsplayground.git \
##    && rm -fr /omicsplayground/.git \
#    && chmod -R ugo+rwX /omicsplayground 

#RUN rm -fr /omicsplayground 
#RUN wget https://github.com/bigomics/omicsplayground/archive/master.zip \
#    && unzip master.zip && mv omicsplayground-master omicsplayground \
#    && chmod -R ugo+rwX /omicsplayground 

#------------------------------------------------------------
# Add shiny user to group shiny
#------------------------------------------------------------
RUN groupadd  shiny \
    && useradd --gid shiny --shell /bin/bash --create-home shiny

#------------------------------------------------------------
# Clean up when done.
#------------------------------------------------------------
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN chmod ugo+rwX /tmp && chmod o+t /tmp

#------------------------------------------------------------
# Copy further configuration files into the Docker image
#------------------------------------------------------------
#RUN mkdir -p /var/lib/shiny-server/bookmarks/shiny
#COPY docker/shiny-server.conf /etc/shiny-server/shiny-server.conf
#COPY docker/shiny-server.sh /usr/bin/shiny-server.sh

## EXPOSE 3838
## CMD ["/usr/bin/shiny-server.sh"]
